const assert=require('node:assert/strict'),fs=require('node:fs');
const core=require('../course5052.js'),data=JSON.parse(fs.readFileSync('data/sehs5052/course.json'));
assert.equal(data.lectures.length,6);assert.deepEqual(data.lectures.map(l=>l.pages.length),[72,69,59,77,95,78]);assert.equal(data.questions.length,78);
for(const l of data.lectures){for(const p of l.pages){assert.equal(l.units.filter(u=>u.start<=p.page&&u.end>=p.page).length,1);assert.ok(fs.statSync('dist/'+p.image).size>100)}for(const u of l.units)for(const f of ['zh','en'])assert.ok(u[f].length>5)}
for(const q of data.questions){assert.ok(data.lectures[q.lecture-1].pages[q.page-1]);assert.equal(q.options.length,4);for(const lang of ['zh','en']){assert.ok(q.question[lang]);assert.ok(q.explanation[lang]);assert.equal(new Set(q.options.map(o=>o[lang])).size,4)}}
for(const scope of ['all','foundation','ai',1,2,3,4,5,6]){const sets=new Set();for(let k=0;k<30;k++){const r=core.start(data.questions,scope);assert.ok(core.validRun(r,data.questions));assert.equal(new Set(r.ids).size,10);assert.ok(r.ids.every(id=>core.pool(data.questions,scope).some(q=>q.id===id)));if(scope==='foundation')for(const l of [1,2,3,4])assert.ok(r.ids.filter(id=>data.questions.find(q=>q.id===id).lecture===l).length>=2);sets.add(r.ids.join(','));for(const id of r.ids)r.answers[id]=data.questions.find(q=>q.id===id).correct;assert.equal(core.grade(data.questions,r).score,100);delete r.answers[r.ids[0]];assert.equal(core.grade(data.questions,r).score,90);assert.equal(core.grade(data.questions,r).rows[0].unanswered,true);r.answers[r.ids[0]]=1;assert.equal(core.grade(data.questions,r).score,90)}assert.ok(sets.size>1)}
assert.ok(!core.validRun({ids:['x']},data.questions));assert.equal(data.extensionProbability,.01);
const html=fs.readFileSync('dist/sehs5052.html','utf8');assert.ok(!html.includes('__SEHS5052__'));assert.ok(html.includes('Welcome to Lecture 6'));assert.ok(fs.readFileSync('dist/index.html','utf8').includes('sehs5052.html'));
for(const l of data.lectures)for(const lang of ['both','zh','en']){const r=fs.readFileSync(`dist/reports/SEHS5052_L${l.lecture}_${lang}.html`,'utf8');assert.equal((r.match(/class="page"/g)||[]).length,l.pages.length);assert.ok(r.includes(l.filename));}
console.log('PASS: 450 source pages, 235 bilingual units, 78 bilingual questions, 9 scopes, unique randomized draws/options, correct/incorrect/unanswered scores and 18 reports.');
